if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("CometSSRViewportHints",[],(function(a,b,c,d,e,f){"use strict";e={max:function(a,b){return a<=b},min:function(a,b){return a>=b}};var g=null,h=null,i=[];function a(a){return a==="width"?g:h}function b(a){g=a.width_px,h=a.height_px}function c(a,b,c,d){var e=i.findIndex(function(b){return b.dimension===a&&b.operation===c&&b.result===d});if(e===-1)i.push({dimension:a,numPixels:b,operation:c,result:d});else{var f=c==="min"&&d===!0||c==="max"&&d===!1,g=i[e].numPixels;i[e].numPixels=f?Math.max(g,b):Math.min(g,b)}}function d(){i.length=0}f.check=e;f.useMatchViewportResults=i;f.getDimension=a;f.setDimensions=b;f.addUseMatchViewportResult=c;f.clearUseMatchViewportResults=d}),66);
__d("useMatchViewport",["CometSSRViewportHints","ExecutionEnvironment","react","useLayoutEffect_SAFE_FOR_SSR"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useState;function a(a,b,e){var f=h(function(){if(!d("ExecutionEnvironment").canUseDOM){var c=d("CometSSRViewportHints").getDimension(b);return c!=null?d("CometSSRViewportHints").check[a](c,e):!1}return!!window.matchMedia&&window.matchMedia(i(a,b,e)).matches}),g=f[0],j=f[1];d("ExecutionEnvironment").canUseDOM||d("CometSSRViewportHints").addUseMatchViewportResult(b,e,a,g);c("useLayoutEffect_SAFE_FOR_SSR")(function(){if(!window.matchMedia)return;var c=i(a,b,e),d=window.matchMedia(c),f=function(a){return j(a.matches)};d.addListener(f);return function(){return d.removeListener(f)}},[a,b,e]);return g}function i(a,b,c){return"("+a+"-"+b+": "+c+"px)"}g["default"]=a}),98);
__d("useProfileCometIsCenteredLayout",["CometLeftRailLayoutContext","CometRouteRenderType","react","useMatchViewport"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){var a=h(c("CometLeftRailLayoutContext")),b=d("CometRouteRenderType").useIsHosted();a=a||b;b=a?1259:899;return c("useMatchViewport")("max","width",b)}g["default"]=a}),98);
__d("CometSSRBtoaPolyfill",[],(function(a,b,c,d,e,f){"use strict";var g="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";function a(a){a=String(a);var b=a.length%3,c,d,e,f="",h=0;for(;h<a.length;){c=a.charCodeAt(h++);d=a.charCodeAt(h++);e=a.charCodeAt(h++);if(c>255||d>255||e>255)throw new TypeError("Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.");c=c<<16|d<<8|e;f+=g.charAt(c>>18&63)+g.charAt(c>>12&63)+g.charAt(c>>6&63)+g.charAt(c&63)}return b?f.slice(0,b-3)+"===".substring(b):f}f["default"]=a}),66);
__d("CometSSRMarkupMode",[],(function(a,b,c,d,e,f){"use strict";var g="ssr";function a(a){g=a}function b(){return g}f.setSSRMarkupMode=a;f.getSSRMarkupMode=b}),66);
__d("CometSSRDOMPolyfill",["CometSSRBtoaPolyfill","CometSSRMarkupMode","CometSSRViewportHints","Env"],(function(a,b,c,d,e,f,g){"use strict";var h=function(){function a(a){var b=this;this.$1=a.href;Object.keys(a).forEach(function(c){Object.defineProperty(b,c,{value:a[c],writable:!1})})}var b=a.prototype;b.toString=function(){return this.$1};b.valueOf=function(){return this.$1};return a}();function a(a){d("CometSSRViewportHints").setDimensions(a)}function b(a){window.document=window.document||{},(window.location==null||Object.prototype.toString.call(window.location)==="[object Object]")&&(window.location=new h(a)),window.document.location=window.location}function i(a){window.__comet_ssr_is_server_env_DO_NOT_USE=!0,window.__flight_execution_mode_DO_NOT_USE=a}function j(){window.atob=window.__atob,window.btoa=c("CometSSRBtoaPolyfill")}function e(a){switch(a){case"adsmanager":l();break;case"flight":k("flight");break;case"entrypoint":m();break;case"email":k("ssr");d("CometSSRMarkupMode").setSSRMarkupMode("markup_only");break;default:k("ssr");break}}function k(a){i(a),j()}function l(){k("ssr"),window.Event=function(){},window.navigator={},window.URL=o(),window.FormData=function(){},window.document=window.document||{},n(window.document),Object.defineProperty(window.document,"cookie",{value:""})}function m(){l()}function n(a){a.getElementById=function(){return null},a.querySelector=function(){return null},a.querySelectorAll=function(){return[]}}function f(a){for(var b in a)c("Env")[b]=a[b]}function o(){return function(){this.searchParams={get:function(){}}}}g.setViewportDimensionsGuess=a;g.setWindowLocation=b;g.defineGlobals=e;g.flushJSEnv=f}),98);
__d("CometSSRServerJSPayloadUtils",["ErrorGuard","HasteSupportData","ServerJS"],(function(a,b,c,d,e,f,g){"use strict";var h="";function a(a){d("HasteSupportData").handle(a.hsdp);c("ErrorGuard").skipGuardGlobal(!0);new(c("ServerJS"))().handle(a.jsmods);return h}function e(c,d,e){var a;typeof c==="string"?a=b.call(null,c):a=c;c=a[d].apply(a,e);c===void 0&&(c="");h=JSON.stringify(c)}g.handlePayload=a;g.invokeAndCaptureReturnValue=e}),98);/*FB_PKG_DELIM*/
__d("CometDeferredDialogTrigger.react",["react","useCometDeferredDialog"],(function(a,b,c,d,e,f,g){"use strict";d("react");var h=d("react").useCallback;function a(a){var b=a.children,d=a.dialogProps,e=a.dialogResource,f=a.fallback,g=a.onHide;a=a.onShow;var i=a===void 0?function(){}:a,j=c("useCometDeferredDialog")(e,f);a=h(function(){j(d,g),i()},[j,d,g,i]);return b(a)}g["default"]=a}),98);
__d("useGamingVideoDestinationLoggingContext",["GamingVideoDestinationLoggingContext","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useContext;function a(){return h(c("GamingVideoDestinationLoggingContext"))}g["default"]=a}),98);
__d("useShallowEqualMemo",["shallowEqual","useCustomEqualityMemo"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("useCustomEqualityMemo")(a,c("shallowEqual"))}g["default"]=a}),98);
__d("CometGamingDestinationSurfaceLoggingContainer",["GamingVideoDestinationLoggingContext","react","useGamingVideoDestinationLoggingContext","useShallowEqualMemo"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a){var b=a.children;a=babelHelpers.objectWithoutPropertiesLoose(a,["children"]);var d=c("useGamingVideoDestinationLoggingContext")();d=c("useShallowEqualMemo")(babelHelpers["extends"]({},d,a));return h.jsx(c("GamingVideoDestinationLoggingContext").Provider,{value:d,children:b})}a.displayName=a.name+" [from "+f.id+"]";g["default"]=a}),98);
__d("InstantGameContextType",[],(function(a,b,c,d,e,f){a=Object.freeze({THREAD:"THREAD",GROUP:"GROUP",STORY:"STORY",SOLO:"SOLO",LINK:"LINK",MATCH:"MATCH",GENERIC:"GENERIC"});f["default"]=a}),66);
__d("XCometGamingArenaHomeControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/gaming/tournaments/",Object.freeze({open_create_tournament_form:!1}),void 0);b=a;g["default"]=b}),98);
__d("XCometGamingGamingProfileControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/gaming/me/{?feature}/{?id}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);