if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }

__d("useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql",[],(function(a,b,c,d,e,f){"use strict";a={argumentDefinitions:[{kind:"RootArgument",name:"scale"}],kind:"Fragment",metadata:null,name:"useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo",selections:[{alias:"viewer_image",args:[{kind:"Literal",name:"context",value:"comet_media_viewer"},{kind:"Literal",name:"height",value:1e6},{kind:"Variable",name:"scale",variableName:"scale"},{kind:"Literal",name:"width",value:1e6}],concreteType:"Image",kind:"LinkedField",name:"image",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"uri",storageKey:null}],storageKey:null},{args:null,kind:"FragmentSpread",name:"useCometPhotoViewerPlaceholderPassthroughProps_photo"}],type:"Photo",abstractKey:null};e.exports=a}),null);
__d("getCometMediaURL_media.graphql",[],(function(a,b,c,d,e,f){"use strict";a={kind:"InlineDataFragment",name:"getCometMediaURL_media"};e.exports=a}),null);
__d("useCometMediaURL_media.graphql",[],(function(a,b,c,d,e,f){"use strict";a=function(){var a={alias:null,args:null,kind:"ScalarField",name:"id",storageKey:null};a=[a,{alias:null,args:null,concreteType:null,kind:"LinkedField",name:"owner",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"__typename",storageKey:null},a,{kind:"InlineFragment",selections:[{alias:null,args:null,kind:"ScalarField",name:"uri_token",storageKey:null}],type:"Page",abstractKey:null}],storageKey:null}];return{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"useCometMediaURL_media",selections:[{kind:"InlineDataFragmentSpread",name:"getCometMediaURL_media",selections:[{alias:null,args:null,kind:"ScalarField",name:"is_playable",storageKey:null},{kind:"InlineFragment",selections:a,type:"Photo",abstractKey:null},{kind:"InlineFragment",selections:a,type:"Video",abstractKey:null}]}],type:"Media",abstractKey:"__isMedia"}}();e.exports=a}),null);
__d("useCometPhotoViewerPlaceholderPassthroughPropsWithURI",["CometRelay","useCometPhotoViewerPlaceholderPassthroughProps","useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a){var e=a.photo;a=a.productTagReferralCode;e=d("CometRelay").useFragment(h!==void 0?h:h=b("useCometPhotoViewerPlaceholderPassthroughPropsWithURI_photo.graphql"),e);return c("useCometPhotoViewerPlaceholderPassthroughProps")({photo:e,placeholderImageSrc:e==null?void 0:(e=e.viewer_image)==null?void 0:e.uri,productTagReferralCode:a})}g["default"]=a}),98);
__d("XCometPageVanityNoMediasetPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{vanity}/photos/{?set}/{fbid}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPageVanityPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/{vanity}/photos/{set}/{fbid}/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("XCometPhotoControllerRouteBuilder",["jsRouteBuilder"],(function(a,b,c,d,e,f,g){a=c("jsRouteBuilder")("/photo/",Object.freeze({}),void 0);b=a;g["default"]=b}),98);
__d("getCometMediaURL",["CometRelay","XCometPageVanityNoMediasetPhotoControllerRouteBuilder","XCometPageVanityPhotoControllerRouteBuilder","XCometPhotoControllerRouteBuilder","XCometVideoControllerRouteBuilder","getCometMediaURL_media.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,e){var f;a=d("CometRelay").readInlineData(h!==void 0?h:h=b("getCometMediaURL_media.graphql"),a);var g=a==null?void 0:a.id,i=(a==null?void 0:a.is_playable)===!0;f=(f=a==null?void 0:(f=a.owner)==null?void 0:f.uri_token)!=null?f:a==null?void 0:(f=a.owner)==null?void 0:f.id;a=(a==null?void 0:(a=a.owner)==null?void 0:a.__typename)==="Page";if(g==null)return null;if(i)return f==null?null:c("XCometVideoControllerRouteBuilder").buildURL({page_token:f,set:e,story_token:g});else if(a&&f!=null)if(e!=null&&e!=="")return c("XCometPageVanityPhotoControllerRouteBuilder").buildURL({fbid:g,set:e,vanity:f});else return c("XCometPageVanityNoMediasetPhotoControllerRouteBuilder").buildURL({fbid:g,vanity:f});else return c("XCometPhotoControllerRouteBuilder").buildURL({fbid:g,set:e})}g["default"]=a}),98);
__d("useCometMediaURL",["CometRelay","getCometMediaURL","useCometMediaURL_media.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h;function a(a,e){a=d("CometRelay").useFragment(h!==void 0?h:h=b("useCometMediaURL_media.graphql"),a);return c("getCometMediaURL")(a,e)}g["default"]=a}),98);
__d("WarningScreenRenderType",[],(function(a,b,c,d,e,f){a=Object.freeze({FULL_COVER:"FULL_COVER",LIGHTWEIGHT:"LIGHTWEIGHT",POST_COVER:"POST_COVER"});f["default"]=a}),66);